### PR TITLE
Add crate: accel, cuda, rustacuda

### PR DESCRIPTION
**Pull request by eisterman**

### CODE REVIEW

**Comment by anowell** [comment]
Merged. Thanks.

**Comment by eisterman** [comment]
Why the commit is unmerged?

**Comment by anowell** [comment]
Apologies. Must have hit the wrong button. Re-triggerred CI to unblock merge

**Comment by eisterman** [comment]
What is the problem with the CI?

**Comment by anowell** [comment]
Sorry about the delays. Finally fixed CI (which was blocking changes from being published). Also, there are now more eyes on PRs so that I don't continue to be the bottleneck.

Your changes are now live.

**Pull request merged**
